name: 'Bump Chart Version'
description: 'Automatically Bump Helm Chart Version'
inputs:
  chart-name:
    description: 'Chart to be bumped'
    required: true
  bump_strategy:
    description: 'How the chart should be bumped'
    required: false
    default: 'PATCH'

runs:
  using: composite
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: "Install Dependencies"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
    - name: "Version Bump"
      shell: bash
      env:
        BUMP_STRATEGY: ${{ inputs.bump_strategy }}
        CHART_NAME: ${{ inputs.chart_name }}
      run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
