name: 'Bump Chart Version'
description: 'Automatically Bump Helm Chart Version'
inputs:
  chart_name:
    description: 'Chart to be bumped'
    required: true
  bump_strategy:
    description: 'How the chart should be bumped'
    required: false
    default: 'PATCH'

runs:
  using: docker
  image: 'Dockerfile'
  env:
    BUMP_STRATEGY: ${{ inputs.bump_strategy }}
    CHART_NAME: ${{ inputs.chart_name }}
